### ISSUE TITLE
v208/209 is breaking my site by giving "provide"'s priority over the extension itself

### ISSUE THREAD

**Issue by boboldehampsink** [heroku/heroku-buildpack-php#540] opened 2022-02-11 07:54 UTC
Somewhere in my composer.lock is a provide ext-mbstring, and now it won't install the ext-mbstring extension anymore... and my sites need this extension (not the provide). Even requiring ext-mbstring in my composer.json doesn't fix this.

**Comment by dzuelke** [comment] 2022-02-11 08:12
See https://github.com/heroku/heroku-buildpack-php/issues/539#issuecomment-1035903234

Can you try with buildpack branch `composer2installer`, please?

**Comment by boboldehampsink** [comment] 2022-02-11 08:16
@dzuelke that works. But does it favor provide'd ext over native ext's now?

**Comment by boboldehampsink** [comment] 2022-02-11 12:41
Ok thanks for the explanation. So to use native extensions over provide's by dependencies I will always have to explicitly require them in my main composer file?

**Comment by alancwoo** [comment] 2022-02-11 13:33
I just ran into the same issue and am not entirely sure - was it specifically caused by my `composer.json` requiring `ext-pdo_sqlite` (which is not included by default according to [the docs](https://devcenter.heroku.com/articles/php-support#available-built-in-extensions)?

Reading the commits, am I correct that this branch/fix will be merged into 210? Forcing this branch seems to be working for me in the meantime.

**Comment by dzuelke** [comment] 2022-02-11 14:03
> Ok thanks for the explanation. So to use native extensions over provide's by dependencies I will always have to explicitly require them in my main composer file?

Yes. If you think about it, that makes sense - if nothing really requires `ext-mbstring`, it should also not get installed, right?

In practice, though, things that need `ext-mbstring` in frameworks do declare it as a `require` - it doesn't have to be in your `composer.json` root. All packages' dependencies are taken into account by the solver.

**Comment by dzuelke** [comment] 2022-02-11 14:04
> I just ran into the same issue and am not entirely sure - was it specifically caused by my `composer.json` requiring `ext-pdo_sqlite` (which is not included by default according to [the docs](https://devcenter.heroku.com/articles/php-support#available-built-in-extensions)?
> 
> Reading the commits, am I correct that this branch/fix will be merged into 210? Forcing this branch seems to be working for me in the meantime.

Interesting; what makes you think it was `ext-pdo_sqlite`? Can you share build output from the broken and the successful runs? Or what error message(s) did you get?

**Comment by alancwoo** [comment] 2022-02-11 14:06
Sorry I just assumed as this issue mentioned the `ext...` dependencies. I was seeing the following (to be clear I am using dokku):

```
remote: -----> Bootstrapping...
remote: -----> Installing platform packages...
remote:
remote:  !     ERROR: Failed to install system packages!
remote:  !
remote:  !     Your platform requirements (for runtimes and extensions) could
remote:  !     not be resolved to an installable set of dependencies, or a
remote:  !     platform package repository was unreachable.
remote:  !
remote:  !     This usually means that you (or packages you are using) depend
remote:  !     on a combination of PHP versions and/or extensions that are
remote:  !     currently not available on Heroku.
remote:  !
remote:  !     The following is the full output from the installation attempt:
remote:  !
remote:  !     > Loading repositories with available runtimes and extensions
remote:  !     > Updating dependencies
remote:  !     > Your requirements could not be resolved to an installable set of packages.
remote:  !     >
remote:  !     >   Problem 1
remote:  !     >     - php 7.4.27 requires heroku/installer-plugin ^1.6.0 -> no matching package found.
remote:  !     >     - php 8.0.15 requires heroku/installer-plugin ^1.6.0 -> no matching package found.
remote:  !     >     - php 8.1.2 requires heroku/installer-plugin ^1.6.0 -> no matching package found.
remote:  !     >     - symfony/polyfill-ctype v1.24.0 requires php >=7.1 -> satisfiable by php[7.1.33, 7.2.26, 7.2.27, 7.2.28, 7.2.29, 7.2.30, 7.2.31, 7.2.32, 7.2.33, 7.2.34, 7.3.13, 7.3.14, 7.3.15, 7.3.16, 7.3.17, 7.3.18, 7.3.19, 7.3.20, 7.3.21, 7.3.22, 7.3.23, 7.3.24, 7.3.25, 7.3.26, 7.3.27, 7.3.28, 7.3.29, 7.3.30, 7.3.31, 7.3.32, 7.3.33, 7.4.10, 7.4.11, 7.4.12, 7.4.13, 7.4.14, 7.4.15, 7.4.16, 7.4.19, 7.4.2, 7.4.20, 7.4.21, 7.4.22, 7.4.23, 7.4.24, 7.4.25, 7.4.26, 7.4.27, 7.4.3, 7.4.4, 7.4.5, 7.4.6, 7.4.7, 7.4.8, 7.4.9, 8.0.0, 8.0.1, 8.0.10, 8.0.11, 8.0.12, 8.0.13, 8.0.14, 8.0.15, 8.0.2, 8.0.3, 8.0.6, 8.0.7, 8.0.8, 8.0.9, 8.1.0, 8.1.1, 8.1.2].
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.1.0
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.1.1
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.1.33
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.2.26
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.2.27
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.2.28
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.2.29
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.2.30
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.2.31
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.2.32
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.2.33
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.2.34
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.13
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.14
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.15
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.16
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.17
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.18
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.19
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.20
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.21
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.22
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.23
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.24
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.25
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.26
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.27
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.28
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.29
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.30
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.31
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.32
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.33
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.10
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.11
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.12
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.13
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.14
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.15
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.16
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.19
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.2
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.20
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.21
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.22
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.23
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.24
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.25
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.26
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.3
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.4
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.5
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.6
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.7
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.8
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.9
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.0
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.1
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.10
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.11
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.12
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.13
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.14
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.2
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.3
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.6
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.7
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.8
remote:  !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.9
remote:  !     >     - Installation request for symfony/polyfill-ctype v1.24.0 -> satisfiable by symfony/polyfill-ctype[v1.24.0].
remote:  !     >
remote:  !
remote:  !     For reference, the following runtimes are currently available:
remote:  !
remote:  !     PHP:  8.1.2, 8.1.1, 8.1.0, 8.0.15, 8.0.14, 8.0.13, 8.0.12,
remote:  !     8.0.11, 8.0.10, 8.0.9, 8.0.8, 8.0.7, 8.0.6, 8.0.3, 8.0.2,
remote:  !     8.0.1, 8.0.0, 7.4.27, 7.4.26, 7.4.25, 7.4.24, 7.4.23,
remote:  !     7.4.22, 7.4.21, 7.4.20, 7.4.19, 7.4.16, 7.4.15, 7.4.14,
remote:  !     7.4.13, 7.4.12, 7.4.11, 7.4.10, 7.4.9, 7.4.8, 7.4.7,
remote:  !     7.4.6, 7.4.5, 7.4.4, 7.4.3, 7.4.2, 7.3.33, 7.3.32,
remote:  !     7.3.31, 7.3.30, 7.3.29, 7.3.28, 7.3.27, 7.3.26, 7.3.25,
remote:  !     7.3.24, 7.3.23, 7.3.22, 7.3.21, 7.3.20, 7.3.19, 7.3.18,
remote:  !     7.3.17, 7.3.16, 7.3.15, 7.3.14, 7.3.13, 7.2.34, 7.2.33,
remote:  !     7.2.32, 7.2.31, 7.2.30, 7.2.29, 7.2.28, 7.2.27, 7.2.26,
remote:  !     7.1.33
remote:  !     HHVM:
remote:  !
remote:  !     Please verify that all requirements for runtime versions in
remote:  !     'composer.lock' are compatible with the list above, and ensure
remote:  !     all required extensions are available for the desired runtimes.
remote:  !
remote:  !     When choosing a PHP runtimes and extensions, please also ensure
remote:  !     they are available on your app's stack (heroku-18), and select
remote:  !     a different stack if needed after consulting the article below.
remote:  !
remote:  !     Be advised that the heroku-18 stack you're currently using only
remote:  !     supports PHP version 7.1 and later.
remote:  !
remote:  !     For a list of supported runtimes & extensions on Heroku, please
remote:  !     refer to: https://devcenter.heroku.com/articles/php-support
remote:
```

**Comment by dzuelke** [comment] 2022-02-11 14:17
Ah yeah, well, Dokku isn't up to date (they bundle snapshots of this buildpack).

**Closed** 2022-02-11 17:29 UTC
Labels: bug

**Comment by dzuelke** [comment] 2022-02-11 17:50
Fixed and released (#541) to the official stable buildpack channel.

@boboldehampsink, @alancwoo and everyone else, you can now revert your workarounds.

Thank you for your patience and enjoy your weekend!

**Comment by dzuelke** [comment] 2022-02-11 23:25
Docs also here https://devcenter.heroku.com/changelog-items/2353 and here https://devcenter.heroku.com/articles/php-support#treatment-of-extensions-provided-by-userland-packages

**Comment by alancwoo** [comment] 2022-02-14 07:28
> Fixed and released (#541) to the official stable buildpack channel.
> 
> @boboldehampsink, @alancwoo and everyone else, you can now revert your workarounds.
> 
> Thank you for your patience and enjoy your weekend!

@dzuelke thank you so much for the quick updates, we really appreciate your help, especially as a dokku user I understand we can be a bit of a thorn in your side!

**Comment by alancwoo** [comment] 2022-10-24 17:09
@dzuelke I'm really sorry to say but this issue cropped up again in the latest buildpack, locking to v211 allowed me to deploy again, but just wanted to let you know.

**Comment by dzuelke** [comment] 2022-10-24 17:19
That's... surprising, since none of the logic changed after v210 (did you mean locking to v221 maybe?).

Anyway, can you please make a reproduce case, @alancwoo ? I think just uploading your `composer.json` and `composer.lock` would be enough (maybe you can trim down the list of packages, too).

That would be really helpful so I can investigate and implement a fix.

**Comment by dzuelke** [comment] 2022-10-27 14:17
@alancwoo can you provide details please?
