### ISSUE TITLE
Respect Composer "provide" keyword used in composer.json

### ISSUE THREAD

**Issue by holtkamp** [heroku/heroku-buildpack-php#146] opened 2016-02-16 18:42 UTC
The Heroku build process uses Composer, which is great. However not all features seem to be supported...

For example the [provide](https://getcomposer.org/doc/04-schema.md#provide) keyword can be used to indicate that a package 'provides' functionality, so no need for additional installation. 

I encountered this by trying to circumvent the delay in PHP7 and ext-mongodb support in some libraries. Also see https://github.com/alcaeus/mongo-php-adapter/issues/67#issuecomment-184791838

In that case installation of ```ext-mongo``` should be skipped, as it is already 'provided' / imitated by the https://github.com/alcaeus/mongo-php-adapter package...

I know this might be a low priority edge case, but I thought is was worth mentioning it :smile:

**Comment by dzuelke** [comment] 2016-02-16 21:39
Why did you close this @holtkamp ? I think this may be a valid issue (in fact this exact example, with @alcaeus' adapter, is on my todo list to try).

It should be pretty trivial to implement support for this (just need to carry over the provide and replace parts of all dependencies in `composer.lock` when creating the `composer.json` that performs the platform installs), but I think I wanna check with @seldaek tomorrow on this. I had a discussion with @naderman last week about edge cases where this will be a problem, but I don't remember specifics because I was dizzy from eating too much brunch :p

**Comment by dzuelke** [comment] 2016-02-16 21:41
(not low priority, by the way - anything that prevents builds from succeeding is due for ~immediate fixing)

**Comment by holtkamp** [comment] 2016-02-16 21:55
@dzuelke, I closed it because I realized that in the deploy I did not have the ```provide``` section in my own ```composer.json``` file and the documentation at https://github.com/alcaeus/mongo-php-adapter states: 

```
If your project includes a library that requires ext-mongo you need to also specify a provide option in your composer.json: "provide": { "ext-mongo": "1.6.12" }

Due to a limitation in composer you need to specify this in the root package.
```

Especially the last sentence made me start doubting / needing to try that scenario first before anyone spends/wastes time on this. But thanks for the open stance to a 'might be an issue' issue :smile:

**Comment by dzuelke** [comment] 2016-02-16 21:57
Oh. Interesting. I remember a twitter conversation between @alcaeus and @seldaek about this. Need to check details.

**Comment by holtkamp** [comment] 2016-02-17 12:54
Ok, I can confirm, even with the ```provide``` section in the root package (my package), installation will fail with the error mentioned in https://github.com/alcaeus/mongo-php-adapter/issues/67#issuecomment-184791838

**Comment by dzuelke** [comment] 2016-02-17 17:31
Uh oh. This is becoming complicated.

@holtkamp can you please give me a super reduced `composer.json` that triggers this. In my testing, `replace` in the root (or anywhere else) works fine, but `provide` does not.

**Comment by alcaeus** [comment] 2016-02-17 17:34
> In my testing, replace in the root (or anywhere else) works fine, but provide does not.

Uh oh. That's not good. I'll have to take another look but that complicates matters.

**Comment by dzuelke** [comment] 2016-02-17 17:38
I think it has to do with how Composer handles real platform packages. My packages are all called `heroku-sys/ext-mongo` et cetera, so Composer likely behaves differently.

**Comment by dzuelke** [comment] 2016-02-17 18:04
I can sit down with @seldaek the next two days and see if I can get to the bottom of this, so if @holtkamp can come up with a reproduce case and @alcaeus also has a chance to look into it, that'd be good timing!

**Comment by dzuelke** [comment] 2016-02-18 17:52
@holtkamp can you share a minimal `composer.json` that exhibits the issue, just so I can be sure I'm testing against the correct permutation of the problem?

**Comment by alcaeus** [comment] 2016-02-18 18:10
I took a look at composer last night, but didn't get much further than realizing that the DependencySolver does not look for libraries and extensions. That's where I stopped looking since it would take a lot more time to dig into this without any knowledge of how composer works internally. I'll have to leave that to people actually familiar with the composer source.

**Comment by holtkamp** [comment] 2016-02-18 20:11
Ok, will try to come up with something this week, but you know how it goes with the time, it kinda "flies" ;)

**Comment by holtkamp** [comment] 2016-02-18 20:38
Ok, better not postpone stuff, here it is:

```json
{
  "provide": {
    "ext-mongo": "1.6.12"
  },
  "require": {
    "php": "^7.0",
    "alcaeus/mongo-php-adapter": "dev-master",
    "doctrine/mongodb": "dev-master"
  }
}
```

Results in 

```
git push heroku master    
Counting objects: 6, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 3.22 KiB | 0 bytes/s, done.
Total 6 (delta 3), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Using set buildpack heroku/php
remote: -----> PHP app detected
remote: -----> Bootstrapping...
remote: -----> Installing system packages...
remote: 
remote:  !     ERROR: Failed to install system packages.
remote:        
remote:        Your platform requirements (for runtimes and extensions) could
remote:        not be resolved to an installable set of dependencies, or a
remote:        repository was unreachable.
remote:        
remote:        Full error information from installation attempt:
remote:        
remote:        > Loading repositories with available runtimes and extensions
remote:        > 
remote:        > Your requirements could not be resolved to an installable set of packages.
remote:        > 
remote:        >   Problem 1
remote:        >     - ext-mongo 1.6.12 requires php 5.5.* -> no matching package found.
remote:        >     - ext-mongo 1.6.12 requires php 5.6.* -> no matching package found.
remote:        >     - doctrine/mongodb dev-master requires ext-mongo ^1.5 -> satisfiable by ext-mongo[1.6.12].
remote:        >     - Installation request for doctrine/mongodb dev-master -> satisfiable by doctrine/mongodb[dev-master].
remote:        > 
remote:        
remote:        Please verify that all requirements for runtime versions in
remote:        'composer.lock' are compatible with the list below, and ensure
remote:        all required extensions are available for the desired runtimes.
remote:        
remote:        For reference, the following runtimes are currently available:
remote:        
remote:        PHP:  7.0.3, 7.0.2, 7.0.1, 7.0.0, 5.6.18, 5.6.17, 5.6.16, 
remote:        5.5.32, 5.5.31, 5.5.30

```

My environment:

```
php -v
PHP 7.0.3 (cli) (built: Feb  6 2016 03:16:24) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```

When I remove the ```"doctrine/mongodb": "dev-master"``` part and running a ```composer update``` the build succeeds when pushing these changes to Heroku...

**Comment by dzuelke** [comment] 2016-02-21 20:22
What happens if you do `replace` in your root `composer.json` @holtkamp ? Does that still work for a local "composer install"? If so, I can add support for that in the buildpack.

**Comment by holtkamp** [comment] 2016-02-22 08:24
@dzuelke yes, locally it still installs with the ```replace``` keyword in my ```composer.json```. Pushing to Heroku fails but I assume that is what you expected. 

PS, 100% no hurry on this this from my side, we dropped the use of MongoDB in our projects last week anyhow, so if you got other high priority issues...

**Comment by dzuelke** [comment] 2016-02-22 12:07
Okay good to know. I'll push a change later that adds support for this and then you can have a go. Maybe @alcaeus can then change the install instructions to use "replace" in the root rather than "provide".

**Comment by dzuelke** [comment] 2016-02-22 17:44
There is another permutation that I think works as well: if @alcaeus' package says "replace" for `ext-mongo`, and your root `composer.json` explicitly says "require". If I understand composer/composer#2690 correctly, then that might be desired behavior. @naderman and/or @stof can you chime in on this?

**Comment by dzuelke** [comment] 2016-02-23 00:03
Okay I can confirm that works, @alcaeus and @holtkamp (using the "composer-replace" branch since that still has it):

```
{
    "require": {
        "php": "^7.0",
        "alcaeus/mongo-php-adapter": "dev-composer-replace",
        "doctrine/mongodb": "dev-master"
    }
}
```

All is fine because `doctrine/mongodb` requires `ext-mongo`.

If no dependency requires that package, then you need to do it in the `composer.json` root:

```
{
    "require": {
        "php": "^7.0",
        "ext-mongo": "*",
        "alcaeus/mongo-php-adapter": "dev-composer-replace"
    }
}
```

This appears to be the preferred approach according to composer/composer#2690, and it works under all circumstances - both with `ext-foo`, as well as with "non-platform" packages (such as on Heroku, where "ext-foo" gets transformed to "heroku-sys/ext-foo").

**Comment by dzuelke** [comment] 2016-02-23 00:28
You can test this with `heroku buildpacks:set https://github.com/dzuelke/heroku-buildpack-php#develop`, @holtkamp - I'll push to the heroku repo tomorrow if it doesn't blow up (may have/want to rebase again, so I'm keeping it in my forked repo for now).

**Comment by dzuelke** [comment] 2016-02-23 00:29
PR here: alcaeus/mongo-php-adapter#70

**Comment by naderman** [comment] 2016-02-23 11:16
> There is another permutation that I think works as well: if @alcaeus' package says "replace" for ext-mongo, and your root composer.json explicitly says "require". If I understand composer/composer#2690 correctly, then that might be desired behavior. @naderman and/or @stof can you chime in on this?

The only thing that means is, that @alcaeus package will only be installed to fill an ext-mongo requirement, if it is explicitly required in composer.json or a dependency. Meaning, composer won't just go out and search packagist for anything that replaces ext-mongo to fulfill that requirement.

**Comment by dzuelke** [comment] 2016-02-23 11:23
Oh. Hmh. But it still works in this combination, @naderman (unlike other combinations explained in alcaeus/mongo-php-adapter#30).

What *should* work in your opinion? And how should that other package express its replacement of `ext-mongo`? with `replace`?

**Comment by stof** [comment] 2016-02-23 11:28
@dzuelke ``replace`` means ``provide``+``conflict``. So this would prevent installing it when ``ext-mongo`` is installed. So the right behavior depends on whether the adapter accounts for the native extension being installed.

**Comment by dzuelke** [comment] 2016-02-23 11:32
Okay I'll do more testing. It may be that something related to platform package handling is broken inside Composer then; IIRC, require in root and provide in the package did not work, @stof, whereas require did.

**Comment by dzuelke** [comment] 2016-02-28 18:04
This is now fixed, @holtkamp.

We also figured out what the issue is with @alcaeus' adapter; it's a problem in Composer's `ComposerRepository` class, or possibly in the data feed from Packagist. We're addressing that separately. A root level `replace` or `provide` for `ext-mongo` just happens to work and is definitely not the correct long-term solution.

**Closed by dzuelke** 2016-02-28 18:04 UTC

**Comment by holtkamp** [comment] 2016-02-29 08:23
ok, thanks for all the effort!
