### ISSUE TITLE
Missing Lib (libonig.so.4 on deploy with php 7.3.* and composer)

### ISSUE THREAD

**Issue by sicutdeux** [heroku/heroku-buildpack-php#396] opened 2020-02-29 14:37 UTC
Hi, Sorry if i'm not posting this in the right repo, i'm getting this error from this morning, not sure what changed, i was using php 7.2 and was force to update to 7.3 on composer.json to see if this fixes the issue, Using Latest Dokku install, here is the error:

```
remote: PHP Warning:  PHP Startup: Unable to load dynamic library 'mbstring.so' (tried: /app/.heroku/php/lib/php/extensions/no-debug-non-zts-20180731/mbstring.so (libonig.so.4: cannot open shared object file: No such file or directory), 
/app/.heroku/php/lib/php/extensions/no-debug-non-zts-20180731/mbstring.so.so (/app/.heroku/php/lib/php/extensions/no-debug-non-zts-20180731/mbstring.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0      
```  

And my dependency list with problems after this:

```
remote: -----> Installing dependencies...        
remote:        Composer version 1.9.3 2020-02-04 12:58:49        
remote:        PHP Warning:  PHP Startup: Unable to load dynamic library 'mbstring.so' (tried: /app/.heroku/php/lib/php/extensions/no-debug-non-zts-20180731/mbstring.so (libonig.so.4: cannot open shared object file: No such file or directory), /app/.heroku/php/lib/php/extensions/no-debug-non-zts-20180731/mbstring.so.so (/app/.heroku/php/lib/php/extensions/no-debug-non-zts-20180731/mbstring.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0        
remote:        Loading composer repositories with package information        
remote:        Installing dependencies from lock file        
remote:        Your requirements could not be resolved to an installable set of packages.        
remote:                
remote:          Problem 1        
remote:            - Installation request for dompdf/dompdf v0.8.5 -> satisfiable by dompdf/dompdf[v0.8.5].        
remote:            - dompdf/dompdf v0.8.5 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.        
remote:          Problem 2        
remote:            - Installation request for laravel/framework v6.17.1 -> satisfiable by laravel/framework[v6.17.1].        
remote:            - laravel/framework v6.17.1 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.        
remote:          Problem 3        
remote:            - Installation request for lcobucci/jwt 3.3.1 -> satisfiable by lcobucci/jwt[3.3.1].        
remote:            - lcobucci/jwt 3.3.1 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.        
remote:          Problem 4        
remote:            - Installation request for league/commonmark 1.3.1 -> satisfiable by league/commonmark[1.3.1].        
remote:            - league/commonmark 1.3.1 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.        
remote:          Problem 5        
remote:            - laravel/framework v6.17.1 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.        
remote:            - tymon/jwt-auth 1.0.0-rc.5 requires illuminate/auth ^5.1|^6 -> satisfiable by laravel/framework[v6.17.1].        
remote:            - Installation request for tymon/jwt-auth 1.0.0-rc.5 -> satisfiable by tymon/jwt-auth[1.0.0-rc.5].        
remote:                
remote:          To enable extensions, verify that they are enabled in your .ini files:        
remote:            - /app/.heroku/php/etc/php/php.ini        
remote:            - /app/.heroku/php/etc/php/conf.d/000-heroku.ini        
remote:            - /app/.heroku/php/etc/php/conf.d/010-ext-zend_opcache.ini        
remote:            - /app/.heroku/php/etc/php/conf.d/100-ext-gd.ini        
remote:            - /app/.heroku/php/etc/php/conf.d/110-ext-mbstring.ini        
remote:            - /app/.heroku/php/etc/php/conf.d/120-ext-soap.ini        
remote:            - /tmp/buildpacks/custom/conf/php/apm-nostart-overrides/apm-nostart-overrides.ini               
```

Any thoughs? thanks.

**Comment by haggen** [comment] 2020-02-29 16:04
Having the same problem right about now.

**Comment by sicutdeux** [comment] 2020-02-29 16:09
Downgrading exactly to 7.2.26 fixed the issue, not sure why!

**Comment by haggen** [comment] 2020-02-29 16:47
This seems to be the culprit https://github.com/heroku/heroku-buildpack-php/pull/394/commits/fb9a1731d1bdf34360cdf705cd220f54284096bd

Related issue on herokuish repo https://github.com/gliderlabs/herokuish/issues/529

**Comment by sicutdeux** [comment] 2020-02-29 21:29
As of from this i don't know how's is going to address the issue, it should be herokuish or heroku-buildpack-php, this is so confusing.

**Comment by dzuelke** [comment] 2020-03-02 22:03
This is a duplicate of #395 

PHP 7.4 now requires `libonig` for mbstring. PHP 7.4.3, and all other new PHP releases, are now built against that library from the system. Like all changes, this was documented in the Heroku changelog at https://devcenter.heroku.com/changelog-items/1743, so I recommend checking that first next time you're having a similar issue when running this buildpack and its components on your own infrastructure, and draw the necessary conclusions from the listed changes.

Not building PHP against this library is not an option, because our customers require regular expression support in mbstring (see e.g. https://github.com/heroku/heroku-buildpack-php/issues/376#issuecomment-584514059), so we're of course providing that to them - they're paying for a maintained, ever evolving platform.

It's a good example of the constant work that we're having to do to evolve the platform. We can't be static and freeze everything in time just because someone, somewhere, might be piecing some of it's publicly available parts together in a way that might eventually stop working.

If you're using this buildpack together with a third party solution that tries to "be like Heroku", you're doing so at your own risk. You're inevitably taking on a lot of ops responsibilities, and you need to keep your systems up to date. That of course requires time, effort, and sysops knowledge.

One trivial way for Dokku, Herokuish etc to give their users more stability would be to maintain their own S3 bucket with PHP runtime binaries, rather than always downloading from the Heroku S3 bucket, but unfortunately for their users, they're not doing that.

Another area where they are not staying up to date with our changes is our stack image updates, so problems like this one, or like #387, occur on a regular basis. This is 100% Dokku/Herokuish's fault - they're vendoring this buildpack, but using live unmirrored untested binaries off our S3 buckets, instead of hosting things themselves, which then inevitably causes mismatches with the binaries that are of course built against the underlying stack images.

So if something breaks in your Dokku or Herokuish setup, please always direct your bug reports to them first. There should be little confusion regarding responsibilities here.

Ultimately, it's quite similar do that old rule of any software project; in this case, you can have something for free, you can have something that's requires no ops knowledge and maintenance on your behalf, and you can have something that ~always works reliably.

But you can pick only have any two of these three, not all of them, at the same time. One of your choices is Dokku/Herokuish, another is Heroku.

At which point we should mention that on Heroku, there is a free tier for dev/test projects, and a hobby project starts at $7 per month, so it's not much more expensive than the odd good cup of coffee or two).

Running things on Dokku/Herokuish is not free either, since you have to factor in both the (usually pretty small) infrastructure cost as well as the cost of your own time (which, once you factor in opportunity cost, becomes **huge**, which many people don't realize), but you're inevitably already locking yourself into that corner of the "compromise triangle".

**Closed by dzuelke** 2020-03-02 22:03 UTC
