### ISSUE TITLE
Dependency missing for PHP 7.4.3 / 7.3.15

### ISSUE THREAD

**Issue by scasei** [heroku/heroku-buildpack-php#398] opened 2020-03-03 13:29 UTC
Got this error while building with Gitlab AutoDeploy:
PHP Warning:  PHP Startup: Unable to load dynamic library 'mbstring.so' (tried: /app/.heroku/php/lib/php/extensions/no-debug-non-zts-20190902/mbstring.so (libonig.so.4: cannot open shared object file: No such file or directory), /app/.heroku/php/lib/php/extensions/no-debug-non-zts-20190902/mbstring.so.so (/app/.heroku/php/lib/php/extensions/no-debug-non-zts-20190902/mbstring.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
remote: 

So missing libs are:
libonig-dev
libonig4

Multi-Buildpacks eg heroku-buildpack-apt are NOT AN OPTION, php and bundled modules should work without installing additional libraries.

Somebody has same error here:
https://stackoverflow.com/questions/60468025/dokku-php-extension-mbstring-is-missing-when-deploying-laravel-application

**Comment by dzuelke** [comment] 2020-03-03 18:30
This is a duplicate of #395 and #396 

Please raise this issue with GitLab, or Herokuish, which is what GitLab uses internally. They haven't updated their base images, and PHP 7.4 now requires `libonig` on the system. There is nothing we can do about it, it's simply a new requirement of new software.

**Closed by dzuelke** 2020-03-03 18:30 UTC
