### ISSUE TITLE
File "./composer.json" cannot be found in the current directory

### ISSUE THREAD

**Issue by archy-bold** [heroku/heroku-buildpack-php#450] opened 2020-11-27 20:20 UTC
I'm using this buildpack with dokku and it's getting to the point of deploying and hitting the following error:

```
         [RuntimeException]
         File "./composer.json" cannot be found in the current directory

       config [-g|--global] [-e|--editor] [-a|--auth] [--unset] [-l|--list] [-f|--file FILE] [--absolute] [--] [<setting-key>] [<setting-value>]...
       realpath: '': No such file or directory
       setuidgid: fatal: unable to run heroku-php-nginx: file does not exist

         [RuntimeException]
         File "./composer.json" cannot be found in the current directory
```

I'm totally scratching my head as to what's going on as composer.json exists in the project. The error is pretty obtuse too. I can't tell what directory it's working in at that point.

**Comment by archy-bold** [comment] 2020-11-27 21:04
Seems like it's definitely a buildpack issue as I don't get the issue when I use my own old fork of the repository.

**Comment by dzuelke** [comment] 2020-11-28 02:25
You mean is deploys fine, but then fails to start up, right?

Composer is now installed as a package like all other platform dependencies, and performs its own path logic on startup (to append `vendor/bin/` to `$PATH`, mainly). To do that, it registers its own `.profile.d/` script that runs on shell startup.

Can you please `dokku run bash` into the built app and run the following:

```ShellSession
$ echo $PATH
$ pwd
$ ls composer.json
$ PHP_INI_SCAN_DIR= composer config --no-plugins bin-dir
$ realpath "$(PHP_INI_SCAN_DIR= composer config --no-plugins bin-dir)"
$ realpath --version
$ realpath --help
```

And let me know the whole output of all of these commands.

Thanks!

**Comment by archy-bold** [comment] 2020-11-28 15:00
Yeah, I think it deploys ok then tries to start and fails.

On running the above in the container I get the following. I see the error on starting bash even.

```
  [RuntimeException]
  File "./composer.json" cannot be found in the current directory


config [-g|--global] [-e|--editor] [-a|--auth] [--unset] [-l|--list] [-f|--file FILE] [--absolute] [--] [<setting-key>] [<setting-value>]...

realpath: '': No such file or directory
$ echo $PATH
/app/.heroku/php/sbin:/app/.heroku/php/bin:/app/.heroku/php/sbin:/app/.heroku/php/bin:/app/.heroku/php/bin:/app/.heroku/php/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:
$ pwd
/app
$ ls composer.json
composer.json
$ PHP_INI_SCAN_DIR= composer config --no-plugins bin-dir
Cannot create cache directory /app/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /app/.composer/cache/files/, or directory is not writable. Proceeding without cache
vendor/bin
$ realpath "$(PHP_INI_SCAN_DIR= composer config --no-plugins bin-dir)"
Cannot create cache directory /app/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /app/.composer/cache/files/, or directory is not writable. Proceeding witho
ut cache
/app/vendor/bin
$ realpath --version
realpath (GNU coreutils) 8.28
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Padraig Brady.
$ realpath --help
Usage: realpath [OPTION]... FILE...
Print the resolved absolute file name;
all but the last component must exist

  -e, --canonicalize-existing  all components of the path must exist
  -m, --canonicalize-missing   no path components need exist or be a directory
  -L, --logical                resolve '..' components before symlinks
  -P, --physical               resolve symlinks as encountered (default)
  -q, --quiet                  suppress most error messages
      --relative-to=DIR        print the resolved path relative to DIR
      --relative-base=DIR      print absolute paths unless paths below DIR
  -s, --strip, --no-symlinks   don't expand symlinks
  -z, --zero                   end each output line with NUL, not newline

      --help     display this help and exit
      --version  output version information and exit

GNU coreutils online help: <http://www.gnu.org/software/coreutils/>
Report realpath translation bugs to <http://translationproject.org/team/>
Full documentation at: <http://www.gnu.org/software/coreutils/realpath>
or available locally via: info '(coreutils) realpath invocation'
```

**Comment by dzuelke** [comment] 2020-11-28 17:09
Okay, bizarre. Maybe the pwd isn't `/app` at the time the shell sources the `.profile.d/` scripts.

More debugging please:

```ShellSession
$ ps -p $$
$ ls -la .profile.d/
$ cat /etc/profile
$ echo $HOME
```

Are you able to modify the built container image and run it again? That would help the most with debugging, as we could then edit the `.profile.d` script that's responsible and have it dump a bunch of debugging info.

**Comment by archy-bold** [comment] 2020-11-30 16:14
Here's the output of those commands:

```bash
$ ps -p $$
  PID TTY          TIME CMD
   12 ?        00:00:00 bash
$ ls -la .profile.d/
total 32
drwxr-xr-x  2 herokuishuser herokuishuser 4096 Nov 30 16:11 .
drwxr-xr-x 44 herokuishuser herokuishuser 4096 Nov 30 16:11 ..
-rw-r--r--  1 herokuishuser herokuishuser   57 Nov 27 20:19 00-global-env.sh
-rw-r--r--  1 herokuishuser herokuishuser 3491 Nov 27 20:19 01-app-env.sh
-rw-r--r--  1 herokuishuser herokuishuser 1048 Nov 12 16:25 100-php.sh
-rw-r--r--  1 herokuishuser herokuishuser  569 Nov 23 02:57 110-composer.sh
-rw-r--r--  1 herokuishuser herokuishuser   65 Nov 12 18:25 120-apache.sh
-rw-r--r--  1 herokuishuser herokuishuser   43 Nov 12 18:30 130-nginx.sh
-rw-r--r--  1 herokuishuser herokuishuser    0 Nov 27 19:21 WEB_CONCURRENCY.sh
$ cat /etc/profile
# /etc/profile: system-wide .profile file for the Bourne shell (sh(1))
# and Bourne compatible shells (bash(1), ksh(1), ash(1), ...).

if [ "${PS1-}" ]; then
  if [ "${BASH-}" ] && [ "$BASH" != "/bin/sh" ]; then
    # The file bash.bashrc already sets the default PS1.
    # PS1='\h:\w\$ '
    if [ -f /etc/bash.bashrc ]; then
      . /etc/bash.bashrc
    fi
  else
    if [ "`id -u`" -eq 0 ]; then
      PS1='# '
    else
      PS1='$ '
    fi
  fi
fi

if [ -d /etc/profile.d ]; then
  for i in /etc/profile.d/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi
$ echo $HOME
/app
```

The original container is gone but it affects the running container too now; I think since I restarted it. So I can modify any script on that container.

**Comment by archy-bold** [comment] 2020-12-01 11:59
I've hidden all my environment variables. Let me know if there are specific ones you need to see.

```
$ tail -n +1 /etc/profile.d/*.sh | cat                                       
# Make sure the locale variables are set to valid values.
eval $(/usr/bin/locale-check C.UTF-8)
$ tail -n +1 .profile.d/0{0,1}-*.sh | cat
==> .profile.d/00-global-env.sh <==
export CURL_CONNECT_TIMEOUT='5'
export CURL_TIMEOUT='30'

==> .profile.d/01-app-env.sh <==
export ENV_VARS='HIDDEN'
```

**Comment by dzuelke** [comment] 2020-12-01 13:03
Hmm. What about, say, `$PATH`, `$HOME`, are basic non-app variables like those even in that file? Or is it just your DB credentials etc?

Anyway, could you maybe just modify `110-composer.sh` and add `set +x` as the first line and let me know what that produces on container startup?

**Comment by dzuelke** [comment] 2020-12-01 13:15
Also, is there a `.profile` or `.bash_profile` in `/app`? There has to be something like that, because something needs to source all the `.sh` files from `.profile.d/` in the first place.

**Comment by archy-bold** [comment] 2020-12-01 17:36
I see neither of those files.

**Comment by simar0at** [comment] 2020-12-02 17:00
Adding
```json
,
        "compile": [
            "echo cd $APP_PATH > .profile.d/001-cd-app.sh"
        ]
```
to your `composer.json` will fix this issue for the moment.
Seems this does not work because something `cd`s away from `/app` (`$APP_PATH`) during runtime launch.
Something else that fixes this is just setting the `--workdir` on `docker run`or `WORKDIR` in Dockerfile to /app

**Comment by archy-bold** [comment] 2020-12-03 11:15
Thanks @simar0at, that got it working. I substituted the `$APP_PATH` var for `/app` hard-coded but that did it.

**Comment by markuspoerschke** [comment] 2020-12-03 18:32
I had the same problem with the error message:

```
setuidgid: fatal: unable to run heroku-php-nginx: file does not exist
```

My `Procfile` looked the following:

```
web: heroku-php-nginx -C server.nginx public/
```

I changed it to:

```
web: vendor/bin/heroku-php-nginx -C server.nginx public/
```

That solved the problem for me.

**Comment by dzuelke** [comment] 2020-12-03 21:44
@markuspoerschke that's not what we're debating here. Of course that works, since by that time the cwd is `/app`.

This issue is about `vendor/bin/` not being set on the path correctly because the expression that does it (by invoking `composer config bin-dir`) is failing.

@simar0at and @archy-bold can you dig a bit further, and maybe raise this with the Dokku maintainers? I wonder why `/app` isn't the cwd during shell startup, and I also wonder at what point it finally does `cd /app` to start the app.

What is inside `.profile.d/01-app-env.sh`? Only secrets? Or also basics like `$HOME` etc?

**Comment by bjornpost** [comment] 2020-12-04 06:28
@josegonzalez can you shine your light on this issue? 🔦

**Comment by josegonzalez** [comment] 2020-12-04 06:58
Small note while I am looking at it: Looks like the official php-getting-started uses the `vendor/bin/heroku-php-apache2` version in it's [Procfile](https://github.com/heroku/php-getting-started/blob/main/Procfile).

**Comment by josegonzalez** [comment] 2020-12-04 07:40
I dug in a bit, looks like we don't change directories into `$HOME` until [after we load the profile](https://github.com/gliderlabs/herokuish/blob/a86565c3b74fd74d26ae749ced3dc191907eaaf2/include/procfile.bash#L48). That was changed [here](https://github.com/gliderlabs/herokuish/commit/21235d78dfd7060191649f448a6645632c5d5c1e).

We have test app deploys which didn't catch this bug, though none of those include the `heroku/*-getting-started` apps (not that this would have caught the error.

Interestingly, using the [experimental CNB support](https://github.com/dokku/dokku/pull/4209) works fine with the buildpack change - well, assuming that the latest php buildpack is included in the current heroku CNB builder. Looks like they [`chdir` _before_ sourcing files](https://github.com/buildpacks/lifecycle/blob/f47f44084fdac3256011da30047f3824ade97fe1/launch/launcher.go#L60). I guess that's safe?

I'm going to make a change to `gliderlabs/herokuish` to move the `cd $app_path` to after the call to `procfile-setup-home` and before the rest of the env is executed. Should tests pass, I'll merge/release, and then re-test with Dokku to verify that fixes the issue.

Thank you @dzuelke for spending time investigating, it is very much appreciated :) Feel free to continue to pull me in if you think this is a bug related to the Dokku build/run environment vs a buildpack issue.

**Comment by dzuelke** [comment] 2020-12-04 08:36
Okay sounds good, if I understand you right you're changing Dokku to `cd /app` before sourcing profile files now, is that right?

That's definitely the right way to do; there might be all sorts of things in a profile script (also a user's own `.profile` included in the app tree) that assumes the cwd is `$HOME`, just like it would be on a shell.

> Small note while I am looking at it: Looks like the official php-getting-started uses the `vendor/bin/heroku-php-apache2` version in it's [Procfile](https://github.com/heroku/php-getting-started/blob/main/Procfile).

Sure, but that's actually unrelated (I've made a note though to change the `Procfile` there since it's shorter without `vendor/bin/`).

The buildpack has been appending (not prepending, otherwise you end up with fiascos like those Node.js `ls` etc packages from a few years ago) `vendor/bin/` (or, more specifically, `composer config bin-dir`) to `$PATH` for years; this is so that one can run e.g. `phpunit`, but also `heroku-php-apache2`, because they're on the path.

That ultimately results in more portable apps, because a change to the composer config (some apps/frameworks have their binaries just in `bin/` for instance) will not cause the app to fail to start.

But the trouble here is that with a recent change, Composer is now installed as a Composer package, and with that, the setup of `$PATH` was moved from a hardcoded location in `bin/compile` to the normal installer hook we have inside the package itself. But that hook can't have hardcoded paths, it needs to evaluate `composer config bin-dir` at runtime and then figure out the absolute path from that, but for that to work, the cwd must be `/app`, because `/app` contains `composer.json` with (maybe) the `bin-dir` `config` entry.

That's where that error message comes from - the `$PATH` setup logic in a `.profile.d/` script invokes `composer`, but it's not run in `/app`, so there is no `composer.json`. That's why it also happens on a simple run of `bash`, since the profile scripts are also sourced then (as they should be).

The `setuidgid: fatal: unable to run heroku-php-nginx: file does not exist` error is just a symptom, not the cause, and @markuspoerschke's workaround only happens to work because the `$PATH` export isn't otherwise necessary, and the explicit `vendor/bin/…` call executes fine.

**Comment by josegonzalez** [comment] 2020-12-04 08:44
Yeah I'm changing directories there. Its a bit funky Because Of Shell Reasons™, but should work (testing 0.5.21 now).

That explanation makes sense for sure, and was along the lines of what I was thinking. Will circle back and post if it all works :)

**Comment by josegonzalez** [comment] 2020-12-04 09:42
My test deploy of `heroku/php-getting-started` with the updated `Procfile` seems to have worked with `gliderlabs/herokuish:v0.5.21`. Folks seeing this error in Dokku with the latest PHP buildpack should upgrade the `herokuish` package (apt or yum will probably help).

**Comment by archy-bold** [comment] 2020-12-04 10:31
> What is inside .profile.d/01-app-env.sh? Only secrets? Or also basics like $HOME etc?

Here's what's in that file (removed application-level vars and redacted anything sensitive):

```
export APP_KEY='REDACTED'
export BUILDPACK_URL='https://github.com/heroku/heroku-buildpack-php'
export DATABASE_URL='REDACTED'
export DB_CONNECTION='REDACTED'
export DB_DATABASE='REDACTED'
export DB_HOST='REDACTED'
export DB_PASSWORD='REDACTED'
export DB_USERNAME='REDACTED'
export DOKKU_APP_RESTORE='1'
export DOKKU_APP_TYPE='herokuish'
export DOKKU_LETSENCRYPT_EMAIL='REDACTED'
export DOKKU_PROXY_PORT='80'
export DOKKU_PROXY_PORT_MAP='http:80:5000 https:443:5000'
export DOKKU_PROXY_SSL_PORT='443'
export GIT_REV='REDACTED'
export HEROKU_PHP_PLATFORM_REPOSITORIES='REDACTED'
```

**Comment by archy-bold** [comment] 2020-12-04 10:47
But can confirm the update to herokuish 0.5.21 fixed the issue:

```
sudo apt-get update && sudo apt-get install herokuish=0.5.21
```

Thanks @josegonzalez and @dzuelke. I guess this can be closed now?

**Comment by markuspoerschke** [comment] 2020-12-04 16:25
I reverted [my „fix“](https://github.com/heroku/heroku-buildpack-php/issues/450#issuecomment-738204412) and updated to herokuish `0.5.21`. To me the problem looks solved.

Thank you very much for the fix and the detailed explanation.

**Comment by dzuelke** [comment] 2020-12-05 13:57
Glad it's sorted. Closing.

**Closed by dzuelke** 2020-12-05 13:57 UTC
Labels: bug
