### ISSUE TITLE
GD issue when upgrading PHP 8.0.13 to 8.0.14

### ISSUE THREAD

**Issue by dragosprotung** [heroku/heroku-buildpack-php#530] opened 2022-01-14 08:53 UTC
After upgrading PHP 8.0.13 to 8.0.14 I started to see.

`Warning: imagecreatefromstring(): gd-png: libpng warning: Interlace handling should be turned on when using png_read_image`
`Warning: imagecreatefromstring(): gd-png: libpng warning: cHRM: invalid chromaticities`

I am not sure if this is related to https://bugs.php.net/bug.php?id=71316 or not

**Comment by dzuelke** [comment] 2022-01-24 16:16
Similar issue with more info and reproduce images: https://github.com/dompdf/dompdf/issues/2718

[Need to see whether this is ](https://github.com/php/php-src/pull/7615#issuecomment-1007744249) mentions system libgd but we build the one bundled with PHP, so gotta investigate.

@dragosprotung if you downgrade to 8.0.13, the warnings do not appear?

**Comment by dragosprotung** [comment] 2022-01-25 12:28
@dzuelke downgrading to PHP `8.0.13` the warning disappears

**Comment by dzuelke** [comment] 2022-01-27 14:16
Okay this is a change in 7.4.24/8.0.14/8.1.0, see https://github.com/php/php-src/pull/7615 and the comments in there.

I suppose the way to do it now is `@imagecreatefromstring()` etc...

Closing, since we can't do anything about this here; feel free to add your thoughts to that PHP PR or the bug tracker.

**Closed by dzuelke** 2022-01-27 14:16 UTC
